### PR TITLE
Mongo_Toolkit: Updated namespaces to `Adapters`

### LINKED ISSUE #119: Mongo_oM: Namespace update from `External` to `Adapters`
#### Broken rules:

Following confirmation [here](https://github.com/BHoM/BHoM_Adapter/issues/213#issuecomment-631687011) the namespace in this toolkit, for all items except the adapter should have the namespace `BH.oM.Adapters.Radiance` or `BH.Engine.Adapters.Radiance` instead of `BH.oM.Radiance`, etc.

The Adapter namespace should remain at `BH.Adapter.Radiance` instead of `BH.Adapter.External.Radiance`.

#### Suggestions to restore compliance:

As above.

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

Closes #119

@adecler @IsakNaslundBh as I am not sure of the Toolkits dependant on this. 
Could you please help me out in tracking any dependant that will be affected by this?

### Test files

Just check any existing test file.

### CODE REVIEW

**Comment by adecler** [comment]
From the top of my head: 
- DataViz_Toolkit
- BHoMAnalytics_Toolkit

Wee need a method in the reflection engine that gives us that info (we had it with the wheel)

**Comment by alelom** [comment]
> From the top of my head:
> 
> * DataViz_Toolkit
> * BHoMAnalytics_Toolkit
> 
> Wee need a method in the reflection engine that gives us that info (we had it with the wheel)

Could you take care of these @adecler ?

**Comment by adecler** [comment]
This is now superseded by https://github.com/BHoM/Mongo_Toolkit/pull/125
@alelom , can you confirm ?

**Comment by alelom** [comment]
> This is now superseded by https://github.com/BHoM/Mongo_Toolkit/pull/125
@alelom , can you confirm ? 

Confirmed, closing.

**Pull request closed without merging**
