### PR TITLE
Mongo_Adapter: type requests fixed to return all subtypes instead of exact type matches

### LINKED ISSUE #166: Mongo_Adapter: Type requests return exact type matches
#### Description:

Once received a `FilterRequest` with a type `X`, Mongo adapter returns only objects of type `X`, its subtypes excluded. As briefly confirmed with @alelom and @IsakNaslundBh, this seems to be against the general convention used for adapters.

### PR DESCRIPTION
**Pull request by pawelbaran**
### NOTE: Depends on 

https://github.com/BHoM/BHoM_Engine/pull/2965
   
### Issues addressed by this PR

Closes #166

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FMongo%5FToolkit%2F%23167%2DSubtypesQuery&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check core

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check core

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check versioning
@BHoMBot check installer

**Review by FraserGreenroyd — APPROVED** [review]
Test review to check merge status - DO NOT MERGE

**Review by adecler — APPROVED** [review]
Approved based on code inspection and valid BsonDocuments being produced when converting a FilterQuery with this PR

**Pull request merged**
