### PR TITLE
Migration to netstandard 2.0

### LINKED ISSUE #164: Migrate to netstandard 2.0
#### Description:
This is necessary for the Mongo adapter to be used without errors in the zero code tools

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes #164
Also contributes to https://github.com/BHoM/BHoM_Engine/issues/2948

See issue

### Test files
https://burohappold.sharepoint.com/:f:/s/BHoM/EsboSGPjLZtLnEps_y2PcuwBHPDzN2IhZeVyVjA2602rfA?e=Xb1btq
It is also good to test that the BHoM analytics is still working correctly

### CODE REVIEW

**Comment by adecler** [comment]
@BHoMBot check compliance

**Comment by adecler** [comment]
@BHoMBot fix project file ref. 9432328402

**Comment by adecler** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
TaperedProfile you are doing my head in.
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 9637924080

**Review by FraserGreenroyd — APPROVED** [review]
Tested with the end of milestone Mongo scripts and everything still worked. Also tested in conjunction with the other PRs (on other branches) as part of this work. Happy to merge to alpha.

**Pull request merged**
