### PR TITLE
Mongo_Adapter: Upsert behaviour fixed

### LINKED ISSUE #172: Upsert updates wrong objects in the collection
#### Description:

Using Mongo_Adapter in upsert mode `(PushType.UpdateOrCreateOnly`) yields seriously wrong results: due to the fact that the pushed objects are matched by `__Tag__` instead of `BHoM_Guid`, any sort of wonderful updates happens - see the test files.

#### Test files:
On [SharePoint]().

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #172

### Test files

See #172

### Additional comments

This PR introduces one functional change that I think is logical/desirable. Namely, after the change only `IBHoMObjects` are allowed to be pushed, others going to be skipped.

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
Do not think we want to limit to only BHoMObjects.

On Previous projects I have worked on I have used Mongo to store for example `IResults` that do not implement the IBHoMObject interface. Limiting the scope to IBHoMObjects would also not allow for `IGeometry` to be stored.

**Comment by adecler** [comment]
Fully agree with @IsakNaslundBh . Also BHoM_Guid are not reliable as they change when the component creating the objects is rerun. Tags are controlled by the user and therefore more reliable.

**Comment by pawelbaran** [comment]
It tempts me to close this PR as I see no chance for approval, but IMO we may have a design issue around Mongo adapter, taken that we have 2 types of IDs (inbuilt `_id` and `BHoM_Guid`), while we force ourselves to use `__Tag__` instead, which from what I understand should be applicable to multiple objects.

@alelom correct me if I am wrong, but the purpose of `tag` in the adapter is to be applied to all objects being pushed in a given attempt, i.e. as a timestamp or phase marker. However, if used in such a way in Mongo adapter, there is no way to meaningfully relate the documents in Db with objects after push/pull (say, I push 3 bars under tag `MyPush,` then pull one, change it and want to update it in Db - how would the adapter know which one needs to be updated?) Exactly what I have shown in the test file.

It seems to me that the entire design around object persistence in BHoM may be a bit too minimalistic - e.g. in case of `IGeometry,` (or any `IObject`) there is no property that would hold reference to the Db record it represents (I would expect same issue in SQL actually). Not much better with `IBHoMObject`, because as mentioned by @adecler, `BHoM_Guid` is not fully reliable.

Happy to be proven wrong about my considerations.

**Comment by adecler** [comment]
@pawelbaran , the tags are used to group objects that will always be pushed and pulled together. You can make the size of those groups as large or as small as you want and the tag are whatever best describes that group. You can even go as far using the `_id` or the `BHoM_Guid` for the tag if you want but you will rarely want to process objects individually, no ? If that's the case though, we are looking at a new user case for Mongo that was not part of the original intent (i.e. storing and retrieving results of calculations/analytics in the same spirit as Flux). For that, we might want to consider an additional way of pushing data with Mongo but it should not replace the existing solution in my opinion.

**Comment by jamesramsden-bh** [comment]
It seems that this PR is proposing a feature change rather than a bug fix. What is there currently works perfectly well, and I wouldn't want to see the current functionality replaced. To meet @pawelbaran 's needs, a better solution might be to retain existing functionality, and allow for optional filtering of the upsert behaviour via an actionConfig setting?

**Comment by pawelbaran** [comment]
I would disagree with you @jamesramsden-bh - the current functionality of Push/Update does not work, which is clearly shown in the test script linked in the issue. Although we can observe a certain amount of tribal knowledge among the team that usually prevents from 'misuse' of the feature (which actually is not misuse IMO, taken the adapter does something else than it claims to do), I would still opt to either properly fix or disable it.

As discussed with @FraserGreenroyd, I am keeping this PR open for a purpose, until someone bothers to open the test file and reflects on what is explained as a bug. No need to say I stumbled upon it when trying to use the adapter in practice, with disastrous consequences to my data...

Having said that, I am happy with this PR being closed as soon as it is acknowledged that we actually have an issue instead of just pushing back to defend the malfunctioning status quo.

**Comment by jamesramsden-bh** [comment]
@pawelbaran , I've now opened up the test script. While I can replicate the behaviour under question, I can also see that the `tag` is not set on the push adapters. Assign tags to your items (both on the initial push and on upsert), and it works correctly. 

Modified test file added to your test folder linked above.

**Comment by pawelbaran** [comment]
Thanks @jamesramsden-bh for having another look - sounds like we are getting somewhere 😉 I deducted the mechanics from the code, and of course I could hack it on my end to simply make things work, but I am not sure if this is the right approach.

I am afraid we have a fundamental issue here, with the following symptoms:
- need to manually set individual tag to each object being pushed (far from the standards set by any contemporary ORMs, also different from other adapters that we have)
- silent failures
- inability to meaningfully push any objects that do not inherit from `BHoMObject` because of lack of `Tags` property
- complete madness to start if someone without the tribal knowledge sets duplicate tags (e.g. empty tag 😉)

...so my point is that it may be worth thinking of the origin of the problem (fundamental issue described above) first, before adding yet another hack, in yet another place. My thoughts run in two directions:
- rethinking the design of the adapter (I already lost my hope, having seen the previous answers)
- adding warnings/errors/automatic behaviours like:
    - if you push a `BHoMObject`, automatically copy its `BHoMGuid` to `Tags`
    - if you push a `non-BHoMObject`, raise a warning saying your data will not be trackable any more

Thoughts?

**Comment by jamesramsden-bh** [comment]
Agreed that the current workflow is not very intuitive, but a wider discussion on how/whether to improve it is beyond the scope of this page, which should be limited to approving, rejecting or reviewing a particular PR. 

Since this PR addresses an issue which is not broken (by design, as per @adecler 's comment above) I don't consider this a 'fix' to upsert behaviour, so I can't support this PR being merged. 

It's worth noting that I have used the current upsert functionality successfully on a previous project. FWIW, merging this PR would break my (and any other) old scripts which use the functionality as it currently stands. 

Happy to continue this discussion on improving the Mongo TK, but it needs to take place on a wider platform than this PR.

**Comment by pawelbaran** [comment]
Agreed with the need for a wider discussion about the topic @jamesramsden-bh, also understood the implications of merging this PR, which I am not aiming to merge any more. I keep it open because I can't agree with the statement that the issue is not broken, as long as the following is not the standard we approve in BHoM (let me quote my own self):
> * need to manually set individual tag to each object being pushed (far from the standards set by any contemporary ORMs, also different from other adapters that we have)
> * silent failures
> * inability to meaningfully push any objects that do not inherit from `BHoMObject` because of lack of `Tags` property
> * complete madness to start if someone without the tribal knowledge sets duplicate tags (e.g. empty tag 😉)

Happy to have a constructive discussion about potential solutions, but not sure if there is any interest in the wider team (it does not feel like that, taken the previous responses). Meanwhile, please remember this is an open source adapter so it is likely to be used by the wider community, which may not know about all the intricacies that have been introduced by design but never documented.

**Pull request closed without merging**
