### PR TITLE
Upgrade Mongo Bson package

### LINKED ISSUE #117: Upgrade Mongo Bson package
#### Suggestions to restore compliance:
Update to Bson 2.10.4

### PR DESCRIPTION
**Pull request by adecler**
### NOTE: Depends on 
No dependency but would be nice to merge at the same time as https://github.com/BHoM/BHoM_Engine/pull/1876

   
### Issues addressed by this PR

Closes #117

### CODE REVIEW

**Comment by alelom** [comment]
Same for me, I get @IsakNaslundBh 's error if opening in VS Express 2015. 
Instead, VS 2017 Community loads and compiles fine.

**Comment by IsakNaslundBh** [comment]
Not sure if we should merge this, if it does not build for all version of VS that we do support?

**Comment by adecler** [comment]
OK, I have switched to Mongo 2.9.3 and it solves the issue. Since that version also fixes teh bug we had with Serialisation of `MultiStorey`, I am happy to keep it that way for now.

In the long run, we need to make a decision though:
- Either we keep providing support for the ~~dinosaurs~~ people out there that are still using VS2015
- Or we keep ourselves up to date with the latest Mongo has two offer 

My thinking is that we can upgrade Mongo only when we need to (i.e. when the newer version fixes a bug we are facing with 2.9.3). That way we keep support for VS2015 for as long as possible. 

I will update Mongo version in the engine and Versioning PRs as well. If you are happy with that solution, then those 3 Prs are ready for review and merging.

**Comment by IsakNaslundBh** [comment]
All now builds on my machine as well!

**Pull request merged**
